name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package --no-transfer-progress

    - name: Run tests
      run: mvn test

    - name: Upload artifact (JAR)
      uses: actions/upload-artifact@v3
      with:
        name: fredyhoyos-jar
        path: target/*.jar

    - name: Deploy to server via SSH
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          # Parar el servicio (si lo hay)
          sudo systemctl stop fredyhoyos || true
          # Copiar el JAR nuevo
          scp target/fredyhoyos-0.0.1-SNAPSHOT.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/fredyhoyos.jar
          # Iniciar el servicio o ejecutar la app
          nohup java -jar /home/${{ secrets.SERVER_USER }}/fredyhoyos.jar > app.log 2>&1 &
